# global settings
title: "Seldonian Toolkit Tutorials"
description: "Learn how to build Seldonian algorithms"
permalink: "/stories/:title"
url: https://seldonian-toolkit.github.io/Tutorials
relative_permalinks: false


# build settings
# Syntax highlighting
highlighter: rouge
markdown: kramdown

include: ["_tutorials"]
exclude: ["script", "Gemfile", "Gemfile.lock", "Rakefile", "README.md", "package.json", "node_modules"]
plugins_dir: ./_plugins
plugins:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-octicons
  - jekyll

sass:
  style: :compressed
  # Where you keep your scss files
  sass_dir: assets/css/
  # Where sass should look for other scss
  load_paths:
    - node_modules/

collections:
  - tutorials
